#!/bin/sh


# GH Game Link Dumper v0.2

# Part of the RealArcade Wrapper Killer

# esc0rtd3w 2018

baseURL="http://www.gamehouse.com/"
baseURLDG="http://www.gamehouse.com/download-games/"
baseURLWeb="http://www.gamehouse.com/#/games/"
baseURLRGSFree="http://games-dl2.real.com/gameconsole/games/demorgses/"
baseURLRGSFull="http://games-dl2.real.com/gameconsole/games/demorgses/"
baseURLRGA1="http://games-dl2.real.com/gameconsole/realarcadev21/games/am-"
baseURLRGA2="http://games-dl2.real.com/gameconsole/realarcadev21/games/am-"
baseURLRGA2Free="http://games-dl2.real.com/gameconsole/realarcadev21/games/amg-"
baseURLRGA3="http://games-dl2.real.com/gameconsole/realarcadev21/games/dip/"
baseURLRGA4="http://games-dl.gamehouse.com/zylom/ghmigration/"
baseURLRFS="http://games-dl.gamehouse.com/gamehouse/pc/"
baseURLRFSAM="http://games-dl.gamehouse.com/gamehouse/pc/"
baseURLRFSAMIndex="http://profiler-cdn.am.gamehouse.com/gamehouse/pc/"
baseURLRFSEXE="http://www.gamehouse.com/game/download/"
baseURLRFSGH="http://games-dl.gamehouse.com/gamehouse/pc/"

inputJSON="games-windows.json"

outputText="games-windows-links.txt"
outputTextCID="games-windows-cid.txt"
outputTextWeb="games-windows-web.txt"

outputHTML="games-windows-links.html"
outputHTMLRGSFree="games-windows-links-rgs-free.html"
outputHTMLRGSFull="games-windows-links-rgs-full.html"
outputHTMLRGA1="games-windows-links-rga-v1.html"
outputHTMLRGA2="games-windows-links-rga-v2.html"
outputHTMLRGA2Free="games-windows-links-rga-v2-free.html"
outputHTMLRGA3="games-windows-links-rga-v3.html"
outputHTMLRGA4="games-windows-links-rga-v4.html"
outputHTMLRFSAM="games-windows-links-rfs-am.html"
outputHTMLRFSRFSIndex="games-windows-links-rfsindex-am.html"
outputHTMLRFSEXE="games-windows-links-rfs-exe.html"
outputHTMLRFSGH="games-windows-links-rfs-gh.html"

outputTMP="dump.tmp"

dumpText="games-windows-dump-list.txt"
dumpTextCID="games-windows-cid-dump-list.txt"

dumpIni="games-windows-dump-list.ini"
dumpXML="games-windows-dump-list.xml"

jsonWindows="games-windows.json"
jsonOnline="games-online.json"
jsonAll="games-full.json"


na="NO_DATA"

extRgsFree="_free.rgs"
extRgsFull="_full.rgs"
extRga=".rga"
extRfs=".rfs"

testPage="http://www.gamehouse.com/download-games/experiment"

#wgetHeader="--header=\"Cookie: gamehouseuser=true\" --header=\"User-Agent: RealArcade Wrapper Killer v5.7.1\""

# Data Gathering URL
# http://www.gamehouse.com/datagathering/actiontracking?actiontrackingkindid=225&actiontrackingsourceid=4458


removeOldFiles(){

	rm "$outputText"
	rm "$outputTextCID"
	rm "$outputTextWeb"
	rm "$outputHTML"
	rm "$outputHTMLRGSFree"
	rm "$outputHTMLRGSFull"
	rm "$outputHTMLRGA1"
	rm "$outputHTMLRGA2"
	rm "$outputHTMLRGA2Free"
	rm "$outputHTMLRGA3"
	rm "$outputHTMLRGA4"
	rm "$outputHTMLRFSAM"
	rm "$outputHTMLRFSRFSIndex"
	rm "$outputHTMLRFSEXE"
	rm "$outputHTMLRFSGH"
	rm "$outputHTMLRFSGH"
	rm "$outputHTMLRFSGH"
	rm "$dumpIni"
	rm "$dumpXML"

}

dumpWebToJSON(){

	wget -d --header="Cookie: gamehouseuser=true"  -O "$jsonWindows" "http://www.gamehouse.com/games.json?gametype=download&genre=all&sorting=name&count=4000&filterType=null"

	#wget -d --header="Cookie: gamehouseuser=true" -O "$jsonOnline" "http://www.gamehouse.com/games.json?gametype=online&genre=all&sorting=name&count=4000&filterType=null"

	#wget -d --header="Cookie: gamehouseuser=true" -O "$jsonAll" "http://www.gamehouse.com/games.json?gametype=null&genre=all&sorting=name&count=4000&filterType=null"

}


dumpGamesToList(){

	removeOldFiles

	clear
	echo "Building List From \"$inputJSON\""
	echo ""
	echo ""

	getNameFromJSON=$(grep -Po '"url":.*?[^\\]"' "$inputJSON" | cut -f2 -d":" | cut -c3- | sed 's/"$//' | cut -c16-)
	nameDashes=$(echo "$getNameFromJSON")
	nameNoDashes=$(echo "$getNameFromJSON" | sed -e 's|["'-']||g')

	#grep -Po '"url":.*?[^\\]"' "$inputJSON" | cut -f2 -d":" | cut -c2- | sed 's/"$//'>"$outputTMP"
	#grep -Po '"url":.*?[^\\]"' "$inputJSON" | cut -f2 -d":" | cut -c3- | sed 's/"$//' | cut -c16- > "$outputTMP"

	echo "$getNameFromJSON" > "$outputTMP"

	# Create Files With Links
	while read -r line
	do
		nameDashes=$(echo "$line")
		nameNoDashes=$(echo "$line" | sed -e 's|["'-']||g')
		nameFirstLetter=$(echo "$line" | sed -e "{ s/^\(.\).*/\1/ ; q }")

		# Output Text File
		echo "$baseURLDG$line">>"$outputText"
		echo "$baseURLWeb$line">>"$outputTextWeb"

		## Output HTML Files

		# GameHouse Web Page
		echo "<a href=\"$baseURL$nameDashes\" target=\"__blank\">$baseURL$nameDashes</a><br>">>"$outputHTML"

		# RGS Free
		echo "<a href=\"$baseURLRGSFree$nameNoDashes$extRgsFree\" target=\"__blank\">$baseURLRGSFree$nameNoDashes$extRgsFree</a><br>">>"$outputHTMLRGSFree"

		# RGS Full
		echo "<a href=\"$baseURLRGSFull$nameNoDashes$extRgsFull\" target=\"__blank\">$baseURLRGSFull$nameNoDashes$extRgsFull</a><br>">>"$outputHTMLRGSFull"

		# RGA v1
		echo "<a href=\"$baseURLRGA1$nameNoDashes/am-$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA1$nameNoDashes/am-$nameNoDashes.rga</a><br>">>"$outputHTMLRGA1"

		# RGA v2
		echo "<a href=\"$baseURLRGA2$nameNoDashes/am-$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA2$nameNoDashes/am-$nameNoDashes.rga</a><br>">>"$outputHTMLRGA2"

		# RGA v2 Free
		echo "<a href=\"$baseURLRGA2Free$nameNoDashes/am-$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA2Free$nameNoDashes/amg-$nameNoDashes.rga</a><br>">>"$outputHTMLRGA2Free"

		# RGA v3
		echo "<a href=\"$baseURLRGA3$nameNoDashes/$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA3$nameNoDashes/$nameNoDashes.rga</a><br>">>"$outputHTMLRGA3"

		# RGA v4
		echo "<a href=\"$baseURLRGA4$nameNoDashes/$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA4$nameNoDashes/$nameNoDashes.rga</a><br>">>"$outputHTMLRGA4"

		# RFS AM
		echo "<a href=\"$baseURLRFSAM$nameFirstLetter/$nameDashes/$nameDashes.rfs\" target=\"__blank\">$baseURLRFSAM$nameFirstLetter/$nameDashes/$nameDashes.rfs</a><br>">>"$outputHTMLRFSAM"

		# RFSIndex AM
		echo "<a href=\"$baseURLRFSAMIndex$nameFirstLetter/$nameDashes/$nameDashes.rfs.0.rfsindex\" target=\"__blank\">$baseURLRFSAMIndex$nameFirstLetter/$nameDashes/$nameDashes.rfs.0.rfsindex</a><br>">>"$outputHTMLRFSRFSIndex"

		# RFS EXE
		echo "<a href=\"$baseURLRFSEXE$nameDashes.exe\" target=\"__blank\">$baseURLRFSEXE$nameDashes.exe</a><br>">>"$outputHTMLRFSEXE"

		# RFS GH
		echo "<a href=\"$baseURLRFSGH$nameNoDashes.rfs\" target=\"__blank\">$baseURLRFSGH$nameNoDashes.rfs</a><br>">>"$outputHTMLRFSGH"

	done < "$outputTMP"

	rm "$outputTMP"
}


dumpPages(){

	# Reset Game Counter
	gameCounter=0

	# Remove Old Files
	rm "$dumpText"
	rm "$dumpIni"
	rm "$outputTMP"

	# Write INI Dump Header (Done Once Before Loop)
	echo "; Game List Dumped By The RealArcade Wrapper Killer">"$dumpIni"
	echo "">>"$dumpIni"
	echo "">>"$dumpIni"

	# Get Basic Info From Sample Page
	dumpPageToTemp "$testPage"
	osName=$(readDataLayer "operating_system_name")
	playerID=$(readDataLayer "player_id")
	isLoggedIn=$(readDataLayer "is_logged_in")
	isFunticketSubscriber=$(readDataLayer "is_funticket_subscriber")
	isExFunticketTrialSubscriber=$(readDataLayer "is_ex_funticket_trial_subscriber")
	#isFunticketTriuthlSubscriber=$(readDataLayer "is_funticket_triuthl_subscriber")
	isTakeOverActive=$(readDataLayer "is_take_over_active")
	rm "$outputTMP"

	# Write Text Dump Header (Done Once Before Loop)
	echo "Game List Dumped By The RealArcade Wrapper Killer">"$dumpText"
	echo "">>"$dumpText"
	echo "">>"$dumpText"
	echo "">>"$dumpText"
	echo "osName: $osName">>"$dumpText"
	echo "playerID: $playerID">>"$dumpText"
	echo "isLoggedIn: $isLoggedIn">>"$dumpText"
	echo "isFunticketSubscriber: $isFunticketSubscriber">>"$dumpText"
	echo "isExFunticketTrialSubscriber: $isExFunticketTrialSubscriber">>"$dumpText"
	#echo "isFunticketTriuthlSubscriber: $isFunticketTriuthlSubscriber">>"$dumpText"
	echo "isTakeOverActive: $isTakeOverActive">>"$dumpText"
	echo "">>"$dumpText"
	echo "">>"$dumpText"


	# Follow Links and Dump Pages
	while read -r line
	do
		
		dumpPageToTemp "$line"

		# Get Some Info From Web Page
		contentID=$(readContentID)
		nameDashes=$(readNameDashes)
		nameNoDashes=$(readNameNoDashes)

		nameTitle=$(readDataLayer "game_name")
		gamesetName=$(readDataLayer "gameset_name")
		gamesetID=$(readDataLayer "gameset_id")
		gameID=$(readDataLayer "game_id")
		genreName=$(readDataLayer "main_genre_name")
		

		gameCounter=$(($gameCounter + 1))

		echo ""	
		echo ""	
		echo "Game Entry #$gameCounter:"		
		echo ""		
		echo "contentID: $contentID"
		echo "nameTitle: $nameTitle"
		echo "nameDashes: $nameDashes"
		echo "nameNoDashes: $nameNoDashes"
		echo "gamesetName: $gamesetName"
		echo "gamesetID: $gamesetID"
		echo "gameID: $gameID"
		echo "genreName: $genreName"
		echo ""	

		# Write To File
		echo "">>"$dumpText"		
		echo "Game Entry #$gameCounter:">>"$dumpText"	
		echo "">>"$dumpText"
		echo "contentID: $contentID">>"$dumpText"
		echo "nameTitle: $nameTitle">>"$dumpText"
		echo "nameDashes: $nameDashes">>"$dumpText"
		echo "nameNoDashes: $nameNoDashes">>"$dumpText"
		echo "gamesetName: $gamesetName">>"$dumpText"
		echo "gamesetID: $gamesetID">>"$dumpText"
		echo "gameID: $gameID">>"$dumpText"
		echo "genreName: $genreName">>"$dumpText"
		echo ""		

		writeIni
		writeXML

	done < "$outputText"
	
	rm "$outputTMP"
}


writeIni(){

	echo "[$contentID]">>"$dumpIni"		
	echo "name_title=$nameTitle">>"$dumpIni"	
	echo "name_stub=$nameNoDashes">>"$dumpIni"	
	echo "name_web=$nameDashes">>"$dumpIni"	
	echo "installation_id=$na">>"$dumpIni"	
	echo "atoken=$na">>"$dumpIni"
	echo "dmg_legacy=$na">>"$dumpIni"
	echo "dmg_gh=$na">>"$dumpIni"
	echo "dmg_amac=$na">>"$dumpIni"
	echo "rga_legacy=$na">>"$dumpIni"
	echo "rga_gh=$na">>"$dumpIni"
	echo "rga_am=$na">>"$dumpIni"
	echo "rga_amg=$na">>"$dumpIni"
	echo "rgs_free=$na">>"$dumpIni"
	echo "rgs_full=$na">>"$dumpIni"
	echo "rfs=$na">>"$dumpIni"
	echo "rfs_index=$na">>"$dumpIni"
	echo "">>"$dumpIni"

}


writeXML(){

	echo "<!--Game List Dumped By The RealArcade Wrapper Killer-->">>"$dumpXML"
	echo "">>"$dumpXML"
	echo "">>"$dumpXML"
	echo "<dump_root>">>"$dumpXML"
	echo "<game>">>"$dumpXML"
	echo "<entry>$gameCounter</entry>">>"$dumpXML"
	echo "<game_id>$gameID</game_id>">>"$dumpXML"
	echo "<genre>$genreName</genre>">>"$dumpXML"
	echo "<name_title>$nameTitle</name_title>">>"$dumpXML"	
	echo "<name_stub>$nameNoDashes</name_stub>">>"$dumpXML"
	echo "<name_web>$nameDashes</name_web>">>"$dumpXML"
	echo "<gameset_name>$gamesetName</gameset_name>">>"$dumpXML"
	echo "<content_id>$contentID</content_id>">>"$dumpXML"
	echo "<gameset_id>$gamesetID</gameset_id>">>"$dumpXML"
	echo "<game_id>$gameID</game_id>">>"$dumpXML"
	echo "</game>">>"$dumpXML"
	echo "</dump_root>">>"$dumpXML"
	echo "">>"$dumpXML"

}

dumpPageToTemp(){

	wget --header="Cookie: gamehouseuser=true" --header="User-Agent: RealArcade Wrapper Killer v5.7.1" -O "$outputTMP" "$1"

}

readDataLayer(){

	grep "$1" "$outputTMP" | cut -f2 -d":" | cut -c2- | sed 's/,$//' | sed -e 's|["'\'']||g'

}

readContentID(){

	grep "contentid=" "$outputTMP" | cut -f3 -d"=" | cut -f1 -d"&"

}

readNameDashes(){

	grep "review-content-grp').load('/reviews/all/game/" "$outputTMP" | cut -f5 -d"/"

}

readNameNoDashes(){

	grep "review-content-grp').load('/reviews/all/game/" "$outputTMP" | cut -f5 -d"/" | sed -e 's|["'-']||g'

}


dumpWebToJSON
dumpGamesToList
dumpPages
#dumpPagesCidOnly


