#!/bin/sh


# GH Game Link Dumper v0.2

# Part of the RealArcade Wrapper Killer

# esc0rtd3w 2018

baseURL="http://www.gamehouse.com/"
baseURLDG="http://www.gamehouse.com/download-games/"
baseURLWeb="http://www.gamehouse.com/#/games/"
baseURLRGSFree="http://games-dl2.real.com/gameconsole/games/demorgses/"
baseURLRGSFull="http://games-dl2.real.com/gameconsole/games/demorgses/"
baseURLRGA1="http://games-dl2.real.com/gameconsole/realarcadev21/games/am-"
baseURLRGA2="http://games-dl2.real.com/gameconsole/realarcadev21/games/am-"
baseURLRGA2Free="http://games-dl2.real.com/gameconsole/realarcadev21/games/amg-"
baseURLRGA3="http://games-dl2.real.com/gameconsole/realarcadev21/games/dip/"
baseURLRGA4="http://games-dl.gamehouse.com/zylom/ghmigration/"
baseURLRFS="http://games-dl.gamehouse.com/gamehouse/pc/"
baseURLRFSAM="http://games-dl.gamehouse.com/gamehouse/pc/"
baseURLRFSAMIndex="http://profiler-cdn.am.gamehouse.com/gamehouse/pc/"
baseURLRFSEXE="http://www.gamehouse.com/game/download/"
baseURLRFSGH="http://games-dl.gamehouse.com/gamehouse/pc/"

inputJSON="games-windows.json"

outputText="games-windows-links.txt"
outputTextCID="games-windows-cid.txt"
outputTextWeb="games-windows-web.txt"

outputHTML="games-windows-links.html"
outputHTMLRGSFree="games-windows-links-rgs-free.html"
outputHTMLRGSFull="games-windows-links-rgs-full.html"
outputHTMLRGA1="games-windows-links-rga-v1.html"
outputHTMLRGA2="games-windows-links-rga-v2.html"
outputHTMLRGA2Free="games-windows-links-rga-v2-free.html"
outputHTMLRGA3="games-windows-links-rga-v3.html"
outputHTMLRGA4="games-windows-links-rga-v4.html"
outputHTMLRFSAM="games-windows-links-rfs-am.html"
outputHTMLRFSRFSIndex="games-windows-links-rfsindex-am.html"
outputHTMLRFSEXE="games-windows-links-rfs-exe.html"
outputHTMLRFSGH="games-windows-links-rfs-gh.html"

outputTMP="dump.tmp"
outputTMP2="dump2.tmp"

dumpText="games-windows-dump-list.txt"
dumpTextCID="games-windows-cid-dump-list.txt"

dumpIni="games-windows-dump-list.ini"

jsonWindows="games-windows.json"
jsonOnline="games-online.json"
jsonAll="games-full.json"


na="NO_DATA"

extRgsFree="_free.rgs"
extRgsFull="_full.rgs"
extRga=".rga"
extRfs=".rfs"

#wgetHeader="--header=\"Cookie: gamehouseuser=true\" --header=\"User-Agent: RealArcade Wrapper Killer v5.7.1\""

# Data Gathering URL
# http://www.gamehouse.com/datagathering/actiontracking?actiontrackingkindid=225&actiontrackingsourceid=4458


dumpWebToJSON(){

	wget -d --header="Cookie: gamehouseuser=true"  -O "$jsonWindows" "http://www.gamehouse.com/games.json?gametype=download&genre=all&sorting=name&count=4000&filterType=null"

	#wget -d --header="Cookie: gamehouseuser=true" -O "$jsonOnline" "http://www.gamehouse.com/games.json?gametype=online&genre=all&sorting=name&count=4000&filterType=null"

	#wget -d --header="Cookie: gamehouseuser=true" -O "$jsonAll" "http://www.gamehouse.com/games.json?gametype=null&genre=all&sorting=name&count=4000&filterType=null"

}


dumpGamesToList(){
	
	clear
	echo "Building List From \"$inputJSON\""
	echo ""
	echo ""

	getNameFromJSON=$(grep -Po '"url":.*?[^\\]"' "$inputJSON" | cut -f2 -d":" | cut -c3- | sed 's/"$//' | cut -c16-)
	nameDashes=$(echo "$getNameFromJSON")
	nameNoDashes=$(echo "$getNameFromJSON" | sed -e 's|["'-']||g')

	#grep -Po '"url":.*?[^\\]"' "$inputJSON" | cut -f2 -d":" | cut -c2- | sed 's/"$//'>"$outputTMP"
	#grep -Po '"url":.*?[^\\]"' "$inputJSON" | cut -f2 -d":" | cut -c3- | sed 's/"$//' | cut -c16- > "$outputTMP"

	echo "$getNameFromJSON" > "$outputTMP"

	rm "$outputText"
	rm "$outputHTML"

	# Create Files With Links
	while read -r line
	do
		nameDashes=$(echo "$line")
		nameNoDashes=$(echo "$line" | sed -e 's|["'-']||g')
		nameFirstLetter=$(echo "$line" | sed -e "{ s/^\(.\).*/\1/ ; q }")

		# Output Text File
		echo "$baseURLDG$line">>"$outputText"
		echo "$baseURLWeb$line">>"$outputTextWeb"

		## Output HTML Files

		# GameHouse Web Page
		echo "<a href=\"$baseURL$nameDashes\" target=\"__blank\">$baseURL$nameDashes\</a><br>">>"$outputHTML"

		# RGS Free
		echo "<a href=\"$baseURLRGSFree$nameNoDashes$extRgsFree\" target=\"__blank\">$baseURLRGSFree$nameNoDashes$extRgsFree</a><br>">>"$outputHTMLRGSFree"

		# RGS Full
		echo "<a href=\"$baseURLRGSFull$nameNoDashes$extRgsFull\" target=\"__blank\">$baseURLRGSFull$nameNoDashes$extRgsFull</a><br>">>"$outputHTMLRGSFull"

		# RGA v1
		echo "<a href=\"$baseURLRGA1$nameNoDashes/am-$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA1$nameNoDashes/am-$nameNoDashes.rga</a><br>">>"$outputHTMLRGA1"

		# RGA v2
		echo "<a href=\"$baseURLRGA2$nameNoDashes/am-$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA2$nameNoDashes/am-$nameNoDashes.rga</a><br>">>"$outputHTMLRGA2"

		# RGA v2 Free
		echo "<a href=\"$baseURLRGA2Free$nameNoDashes/am-$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA2Free$nameNoDashes/amg-$nameNoDashes.rga</a><br>">>"$outputHTMLRGA2Free"

		# RGA v3
		echo "<a href=\"$baseURLRGA3$nameNoDashes/$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA3$nameNoDashes/$nameNoDashes.rga</a><br>">>"$outputHTMLRGA3"

		# RGA v4
		echo "<a href=\"$baseURLRGA4$nameNoDashes/$nameNoDashes.rga\" target=\"__blank\">$baseURLRGA4$nameNoDashes/$nameNoDashes.rga</a><br>">>"$outputHTMLRGA4"

		# RFS AM
		echo "<a href=\"$baseURLRFSAM$nameFirstLetter/$nameDashes/$nameDashes.rfs\" target=\"__blank\">$baseURLRFSAM$nameFirstLetter/$nameDashes/$nameDashes.rfs</a><br>">>"$outputHTMLRFSAM"

		# RFSIndex AM
		echo "<a href=\"$baseURLRFSAMIndex$nameFirstLetter/$nameDashes/$nameDashes.rfs.0.rfsindex\" target=\"__blank\">$baseURLRFSAMIndex$nameFirstLetter/$nameDashes/$nameDashes.rfs.0.rfsindex</a><br>">>"$outputHTMLRFSRFSIndex"

		# RFS EXE
		echo "<a href=\"$baseURLRFSEXE$nameDashes.exe\" target=\"__blank\">$baseURLRFSEXE$nameDashes.exe</a><br>">>"$outputHTMLRFSEXE"

		# RFS GH
		echo "<a href=\"$baseURLRFSGH$nameNoDashes.rfs\" target=\"__blank\">$baseURLRFSGH$nameNoDashes.rfs</a><br>">>"$outputHTMLRFSGH"

	done < "$outputTMP"

	rm "$outputTMP"
}


dumpPages(){

	
	rm "$dumpText"

	gameCounter=0


	# Write INI Header (Done Once Before Loop)
	echo "; Game List Dumped By The RealArcade Wrapper Killer">"$dumpIni"
	echo "">>"$dumpIni"
	echo "">>"$dumpIni"


	# Follow Links and Dump Pages
	while read -r line
	do
		
		wget --header="Cookie: gamehouseuser=true" --header="User-Agent: RealArcade Wrapper Killer v5.7.1" -O "$outputTMP" "$line"

		# Get Some Info From Web Page
		contentID=$(grep "contentid=" "$outputTMP" | cut -f3 -d"=" | cut -f1 -d"&")
		nameTitle=$(grep "game_name" "$outputTMP" | cut -f2 -d":" | cut -c2- | sed 's/,$//' | sed -e 's|["'\'']||g')
		nameDashes=$(grep "review-content-grp').load('/reviews/all/game/" "$outputTMP" | cut -f5 -d"/")
		nameNoDashes=$(grep "review-content-grp').load('/reviews/all/game/" "$outputTMP" | cut -f5 -d"/" | sed -e 's|["'-']||g')

		gameCounter=$(($gameCounter + 1))

		echo ""	
		echo ""	
		echo "Game Entry #$gameCounter:"		
		echo ""		
		echo "contentID: $contentID"
		echo "nameTitle: $nameTitle"
		echo "nameDashes: $nameDashes"
		echo "nameNoDashes: $nameNoDashes"
		echo ""	

		# Write To File
		echo "">>"$dumpText"		
		echo "Game Entry #$gameCounter:">>"$dumpText"			
		echo "">>"$dumpText"			
		echo "contentID: $contentID">>"$dumpText"	
		echo "nameTitle: $nameTitle">>"$dumpText"	
		echo "nameDashes: $nameDashes">>"$dumpText"	
		echo "nameNoDashes: $nameNoDashes">>"$dumpText"	
		echo ""		

		# Write INI File
		writeIni

	done < "$outputText"
	
	rm "$outputTMP"
}


dumpPagesCidOnly(){

	
	rm "$dumpTextCID"

	gameCounter=0

	# Follow Links and Dump Pages
	while read -r line
	do
		
		wget --header="Cookie: gamehouseuser=true" --header="User-Agent: RealArcade Wrapper Killer v5.7.1" -O "$outputTMP" "$line"

		contentID=$(grep "contentid=" "$outputTMP" | cut -f3 -d"=" | cut -f1 -d"&")

		gameCounter=$(($gameCounter + 1))

		echo ""		
		echo "contentID: $contentID"
		echo ""	

		# Write To File	
		echo "$contentID">>"$dumpTextCID"

	done < "$outputText"
	
	rm "$outputTMP"
	rm "$outputText"
	rm "$outputHTML"
}


writeIni(){

	echo "[$contentID]">>"$dumpIni"		
	echo "name_title=$nameTitle">>"$dumpIni"	
	echo "name_stub=$nameNoDashes">>"$dumpIni"	
	echo "name_web=$nameDashes">>"$dumpIni"	
	echo "installation_id=$na">>"$dumpIni"	
	echo "atoken=$na">>"$dumpIni"
	echo "dmg_legacy=$na">>"$dumpIni"
	echo "dmg_gh=$na">>"$dumpIni"
	echo "dmg_amac=$na">>"$dumpIni"
	echo "rga_legacy=$na">>"$dumpIni"
	echo "rga_gh=$na">>"$dumpIni"
	echo "rga_am=$na">>"$dumpIni"
	echo "rga_amg=$na">>"$dumpIni"
	echo "rgs_free=$na">>"$dumpIni"
	echo "rgs_full=$na">>"$dumpIni"
	echo "rfs=$na">>"$dumpIni"
	echo "rfs_index=$na">>"$dumpIni"
	echo "">>"$dumpIni"

}

dumpWebToJSON
dumpGamesToList
dumpPages
#dumpPagesCidOnly


