#!/bin/bash


# Gamehouse HTML dumper and link retrieval

# Part of the RealArcade Wrapper Killer

# cRypTiCwaRe 2014




getPageLinks()
{

content=$(wget http://www.gamehouse.com/new-games -q -O -)



stripHTMLTagsBase=$(links -dump -width 512 "http://www.gamehouse.com" | cut -c 4-)

stripAllExceptLinksBase=$(lynx -listonly -dump "http://www.gamehouse.com" | sed '1,3d' | cut -c 7-)


stripHTMLTagsNewGames=$(links -dump -width 512 "http://www.gamehouse.com/new-games" | cut -c 4-)

stripAllExceptLinksNewGames=$(lynx -listonly -dump "http://www.gamehouse.com/new-games" | sed '1,3d' | cut -c 7-)


stripHTMLTagsPostDownload=$(links -dump -width 512 "http://www.gamehouse.com/pc/postdownload" | cut -c 4-)
stripAllExceptLinksPostDownload=$(lynx -listonly -dump "http://www.gamehouse.com/pc/postdownload" | sed '1,3d' | cut -c 7-)



pageWindows=$(echo $stripAllExceptLinksNewGames | grep '/download-games/')

pageMac=$(echo $stripAllExceptLinksNewGames | grep '/mac-games/')

pageWindowsOGM=$(echo $stripAllExceptLinksPostDownload | grep '/download/ogm/pc/')




#echo $content


echo $pageWindowsOGM

#echo $pageMac




}



installerRedirectV3()
{

# Set known variables for URL manipulation
base='http://itm.zylom.com/itm/installer/installerRedirect/'
pre='Installer_'
stubName=''
post='.exe'
contentId=''
channel=''
otp=''
trackingId=''
currency=''
price=''
installerVersion=''
lang=''
extraTracking=''
publisher='ghmigration'


funpassAutoUnlockBase='http://activemark.gamehouse.com/autounlock/gettoken?'
funpassAutoUnlockGameSetId='gamesetid='
funpassAutoUnlockContentId='contentid='
funpassAutoUnlockLicenseType='licensetype='



stubLinkBase='http://installer-manager.gamehouse.com/InstallerManager/getinstallersettings?'
stubLinkPart1installationId='installationid=c03dcc3b6ef41468ec1a4dc07143fd4'
stubLinkPart2component='component=acid'
stubLinkPart3version='version=1.00'



echo ''
echo 'Enter the [stubName] and press ENTER:'
echo ''
echo 'Example: puzzlerbraingames'
echo ''
read -p "" stubName
echo ''


echo ''
echo 'Enter the [contentId] and press ENTER:'
echo ''
echo 'Example: 7b692f35e9469fc1975e110bf4e217a7'
echo ''
read -p "" contentId
echo ''


echo ''
echo 'Enter the [channel] and press ENTER:'
echo ''
echo 'Example: z_syn_gh_g12'
echo ''
read -p "" channel
echo ''


echo ''
echo 'Enter the [trackingid] and press ENTER:'
echo ''
echo 'Example: affb9e490b52beeaba62073a45686600'
echo ''
read -p "" trackingId
echo ''


# Original test link:
# http://itm.zylom.com/itm/installer/installerRedirect/Installer_puzzlerbraingames.exe?gameid=7b692f35e9469fc1975e110bf4e217a7&channel=z_syn_gh_g12&otp=&tracking=affb9e490b52beeaba62073a45686600&currency=1&price=60.0&installerversion=&lang=&extratracking=&publisher=ghmigration

# Create a new link from all available input
linkCreate=$(echo "$base$pre$stubname$post?gameid=$contentId&channel=$channel&otp=$opt&tracking=$trackingId&currency=$currency&price=$price&lang=$lang&extratracking=$extraTracking&publisher=$publisher")

# Send the new URL and retrieve the file
linkGet=$(wget $linkCreate -O $pre$stubname$post)




}


getPageLinks
#installerRedirectV3



read pause









