// ----------------------------------------------------------------------------
// ASinstaller.loc
// ----------------------------------------------------------------------------
ASinstaller.loc = {
  //localization text
  en: {
    loc_thank_you_for_choosing:'Thank you for choosing to install',
    loc_step:'Step&nbsp;',
    loc_of:'&nbsp;of&nbsp;',
    loc_setup_options:'Installation Options',
    loc_choose_the_folder:'Choose the folder for your GameHouse games:',
    loc_choose_folder:'Choose Folder',
    loc_bookmark_games_to_my_browser:"Add GameHouse Games to my browser's Favorites menu.",//new
    loc_place_a_short_on_desktop:'Place a shortcut on my desktop for each GameHouse game I download.',
    loc_agreement:'Agreement',
    loc_if_you_agree:'If you agree to the GameHouse ',
    loc_terms_of_service:'End User License Agreement ',
    loc_and:'&nbsp;and ',
    loc_privacy_policy:'Privacy Policy',
    loc_click_i_agree:", click <strong>\"I Agree\"</strong> to continue.",
    loc_i_agree:'I Agree',
    loc_your_game_is_downloading:'Your game is downloading...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game.',
    loc_total_download:'Total Download:',
    loc_download_complete:'Installation Complete!',
    loc_please_wait_while_launch:'Please wait while your game starts',
    //google slides
    loc_free:'Free! ',
    loc_new_way_to_get_online:'GameHouse recommends Google Chrome, <br>a faster way to browse the web.',
    loc_faster_access:'Faster access to your favorite sites',
    loc_search_in_address_bar:'Google Search built into the address bar',
    loc_stable_secure:'Stable and Secure',
    loc_include_chrome:'Include Google Chrome, a faster way to browse the Web. ',
    loc_include_chrome2:'.',
    loc_default_chrome:'Make Google Chrome my default browser',
    loc_by_installing_you_agree_chrome:'Google Chrome  ',
    loc_by_installing_you_agree_chrome2:'.',
    loc_and_chrome:'&nbsp;and ',
    loc_by_installing_you_agree:'By installing this application, you agree to the ',
    loc_terms_of_use:'Terms of Use',
    loc_special_offer:'Special offer. Get it Free.',
    loc_search_from_any_page:'Search with Google from any web page',
    loc_block_popups:'Block annoying pop-ups',
    loc_automatically_fill_out_forms:'Automatically fill out forms for faster online shopping',
    loc_include_toolbar:'Include the free Google Toolbar for Internet Explorer.',
    loc_recommended:'(Recommended)',
    loc_next:'Next',
    loc_opencandy_terms1:'If you accepted this offer, by clicking Next you agree to the&nbsp;',
    loc_opencandy_terms2:'OpenCandy End User License Agreement',
    loc_opencandy_terms3:'',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula.html',
    loc_opencandy_open_text:'We also have this free offer available. Please select whether you would like to install then click below to start your game.',
    loc_opencandy_installed:'Success! Your game was installed!',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'By installing this application, you agree to the  ',
    loc_by_installing_you_agree_chromeGTB2:'.',
    loc_by_installing_you_agree_chromeGTBlink:'Google Terms of Service',
    //for links
    loc_privacy:'privacy',
    loc_terms:'terms',
    loc_game_is_installing_title:'Installing game',
    loc_game_is_installing_text:'Please wait a moment'
  },
  de: {
    loc_thank_you_for_choosing:'Vielen Dank f&uuml;r die Installation von',
    loc_step:'Schritt&nbsp;',
    loc_of:'&nbsp;von&nbsp;',
    loc_setup_options:'Installationsoptionen',
    loc_choose_the_folder:'Bitte w&auml;hle den Ordner aus, in den die Spieldateien kopiert werden sollen. Wir empfehlen, den vorgeschlagenen Ordner zu nutzen.',
    loc_choose_folder:'Ordner auswhlen',
    loc_bookmark_games_to_my_browser:"GameHouse Website unter Favoriten speichern",
    loc_place_a_short_on_desktop:'F&uuml;r jedes Spiel, das ich herunterlade und installiere, eine Desktop-Verkn&uuml;pfung anlegen',
    loc_agreement:'Vereinbarung',
    loc_if_you_agree:'Falls du den ',
    loc_terms_of_service:'Allgemeinen Gesch&auml;ftsbedingungen',
    loc_and:'&nbsp;und den ',
    loc_privacy_policy:'Datenschutzbestimmungen',
    loc_click_i_agree:", klick bitte auf Ich stimme zu.",
    loc_i_agree:'Ich stimme zu',
    loc_your_game_is_downloading:'Dein Spiel wird heruntergeladen ...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game.',
    loc_total_download:'Gesamtgr&ouml;sse:',
    loc_download_complete:'Download abgeschlossen!',
    loc_please_wait_while_launch:'Bitte warte noch, bis das Spiel gestartet wird',
    //google slides
    loc_free:'Gratis! ',
    loc_new_way_to_get_online:'GameHouse empfiehlt Google Chrome, den schnelleren Internet-Browser.',
    loc_faster_access:'Schnellerer Zugriff auf deine Lieblingssites',
    loc_search_in_address_bar:'Die Google-Suche direkt in der Adressleiste',
    loc_stable_secure:'Stabil und sicher',
    loc_include_chrome:'Installier Google Chrome zusammen mit ',
    loc_include_chrome2:'.',
    loc_default_chrome:'Google Chrome zum Standardbrowser machen',
    loc_by_installing_you_agree_chrome:'Durch Installation dieser Anwendung gibst du deine Zustimmung zu den Google-Chrome-',
    loc_by_installing_you_agree_chrome2:'.',
    loc_and_chrome:'&nbsp;und den ',
    loc_by_installing_you_agree:'Durch Installation dieser Anwendung gibst du deine Zustimmung zu den ',
    loc_terms_of_use:'Nutzungsbedingungen',
    loc_special_offer:'Sonderangebot. Hol es dir gratis.',
    loc_search_from_any_page:'Mit Google von jeder Webseite aus suchen',
    loc_block_popups:'L&auml;stige Popup-Fenster blockieren',
    loc_automatically_fill_out_forms:'Schnellere Online-Eink&auml;ufe durch automatisches Ausf&uuml;llen von Formularen',
    loc_include_toolbar:'F&uuml;ge die kostenlose Google-Toolbar f&uuml;r den Internet Explorer hinzu.',
    loc_recommended:'(Empfohlen)',
    loc_next:'Weiter',
    loc_opencandy_terms1:'Wenn Sie dieses Angebot angenommen haben und auf Weiter klicken, erklren Sie sich an die&nbsp;',
    loc_opencandy_terms2:'OpenCandy Endnutzer-Lizenzvereinbarung',
    loc_opencandy_terms3:'&nbsp;gebunden.',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula-de.html',
    loc_opencandy_open_text:'Au&szlig;erdem haben wir dieses Gratis-Angebot f&uuml;r dich. Bitte w&auml;hle aus, ob du es installieren m&ouml;chtest oder nicht. Klicke dann unten, um dein Spiel zu starten.',
    loc_opencandy_installed:'Succesvolle installatie van',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'Durch die Installation dieser Apps erkl&auml;rst du dich mit den ',
    loc_by_installing_you_agree_chromeGTB2:' einverstanden.',
    loc_by_installing_you_agree_chromeGTBlink:'Nutzungsbedingungen von Google ',
    //for links
    loc_privacy:'datenschutz',
    loc_terms:'service',
    loc_game_is_installing_title:'Spiel wird installiert',
    loc_game_is_installing_text:'Bitte warten'
  },
  es: {
    loc_thank_you_for_choosing:'Gracias por instalar',
    loc_step:'Paso&nbsp;',
    loc_of:'&nbsp;de&nbsp;',
    loc_setup_options:'Opciones de instalaci&oacute;n',
    loc_choose_the_folder:'Escoge la carpeta en la que quieres instalar tu juego. Recomendamos que utilices la carpeta ya especificada.',
    loc_choose_folder:'elegir carpeta',
    loc_bookmark_games_to_my_browser:"Marcar GameHouse Games como favorito",
    loc_place_a_short_on_desktop:'Crear un acceso directo en mi escritorio para cada juego que descargo e instalo',
    loc_agreement:'Aceptaci&oacute;n',
    loc_if_you_agree:'Si aceptas los ',
    loc_terms_of_service:'T&eacute;rminos de Servicio',
    loc_and:'&nbsp;y la ',
    loc_privacy_policy:'Pol&iacute;tica de Privacidad',
    loc_click_i_agree:"&nbsp;haz clic en 'acepto' para continuar.",
    loc_i_agree:'acepto',
    loc_your_game_is_downloading:'Tu juego se est&aacute; descargando...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game',
    loc_total_download:'Descarga total:',
    loc_download_complete:'Descarga completa!',
    loc_please_wait_while_launch:'Por favor, espera mientras tu juego se inicia',
    //google slides
    loc_free:'Gratis ',
    loc_new_way_to_get_online:'GameHouse recomienda Google Chrome para navegar por la Red.',
    loc_faster_access:'Accede m&aacute;s r&aacute;pido a tus p&aacute;ginas favoritas',
    loc_search_in_address_bar:'Google Search integrado en la barra de direcciones',
    loc_stable_secure:'Estable y seguro',
    loc_include_chrome:'Incluir Google Chrome junto con ',
    loc_include_chrome2:'.',
    loc_default_chrome:'Establecer Google Chrome como mi navegador predeterminado.',
    loc_by_installing_you_agree_chrome:'Al instalar esta aplicaci&oacute;n, aceptas las ',
    loc_by_installing_you_agree_chrome2:'&nbsp;de Google Chrome.',
    loc_and_chrome:'&nbsp;y la ',
    loc_by_installing_you_agree:'Al instalar esta aplicaci&oacute;n, aceptas las ',
    loc_terms_of_use:'Condiciones del servicio',
    loc_special_offer:'Oferta especial: cons&iacute;guelo gratis.',
    loc_search_from_any_page:'Realiza b&uacute;squedas en Google desde cualquier p&aacute;gina web',
    loc_block_popups:'Bloquea molestos elementos emergentes',
    loc_automatically_fill_out_forms:'Rellena formularios autom&aacute;ticamente para comprar en l&iacute;nea con mayor rapidez',
    loc_include_toolbar:'Incluye la barra de herramientas Google para Internet Explorer',
    loc_recommended:'(Recomendada)',
    loc_next:'Siguiente',
    loc_opencandy_terms1:'Si acept&oacute; esta oferta, al hacer clic en Siguientes estar&aacute; aceptando el&nbsp;',
    loc_opencandy_terms2:'Acuerdo de Licencia para Usuario Final de OpenCandy',
    loc_opencandy_terms3:'',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula-es.html',
    loc_opencandy_open_text:'Tambi&eacute;n tenemos esta oferta gratis a tu disposici&oacute;n. Elige si instalarla o no y despu&eacute;s haz clic abajo para empezar el juego.',
    loc_opencandy_installed:'Success! Your game was installed!',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'Al instalar estas aplicaciones, aceptas las ',
    loc_by_installing_you_agree_chromeGTB2:'.',
    loc_by_installing_you_agree_chromeGTBlink:'Condiciones de servicio de Google',
    //for links
    loc_privacy:'privacy',
    loc_terms:'servicio',
    loc_game_is_installing_title:'Instalando juego',
    loc_game_is_installing_text:'Espera'
  },
  fr: {
    loc_thank_you_for_choosing:"Merci davoir choisi dinstaller",
    loc_step:'Etape&nbsp;',
    loc_of:'&nbsp;sur&nbsp;',
    loc_setup_options:"Options d'installation",
    loc_choose_the_folder:"Choisissez le dossier dans lequel vous souhaitez installer votre jeu. Nous vous conseillons lemplacement s&eacute;lectionn&eacute; par d&eacute;faut.",
    loc_choose_folder:'Choisissez dossier',
    loc_bookmark_games_to_my_browser:"Ajouter les Jeux GameHouse &agrave; mes sites Internet favoris",
    loc_place_a_short_on_desktop:'Cr&eacute;er un raccourci sur mon bureau pour chaque jeu que je t&eacute;l&eacute;charge et installe ',
    loc_agreement:'Acceptation',
    loc_if_you_agree:'Si vous acceptez les ',
    loc_terms_of_service:"Conditions d'utilisation du service",
    loc_and:'&nbsp;et la ',
    loc_privacy_policy:'politique de confidentialit&eacute;',
    loc_click_i_agree:", cliquez sur jaccepte pour continuer.",
    loc_i_agree:'jaccepte',
    loc_your_game_is_downloading:'Votre jeu est en cours de t&eacute;l&eacute;chargement...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game.',
    loc_total_download:'Taille du fichier &agrave; t&eacute;l&eacute;charger  :',
    loc_download_complete:'T&eacute;l&eacute;chargement termin&eacute; !',
    loc_please_wait_while_launch:'Merci de patienter pendant le lancement de votre jeu',
    //google slides
    loc_free:'Gratuit ',
    loc_new_way_to_get_online:'GameHouse recommande Google Chrome pour surfer rapidement sur Internet.',
    loc_faster_access:'Un acc&egrave;s plus rapide &agrave; tous vos sites pr&eacute;f&eacute;r&eacute;s.',
    loc_search_in_address_bar:'Google Search int&eacute;gr&eacute; &agrave; la barre d&#39;adresse de votre navigateur.',
    loc_stable_secure:'Fiable et s&eacute;curis&eacute;.',
    loc_include_chrome:'Inclure Google Chrome &agrave; ',
    loc_include_chrome2:'.',
    loc_default_chrome:'D&eacute;finir Google Chrome comme navigateur par d&eacute;faut.',
    loc_by_installing_you_agree_chrome:'En installant cette application, vous acceptez les ',
    loc_by_installing_you_agree_chrome2:'&nbsp;de Google Chrome.',
    loc_and_chrome:'&nbsp;et la ',
    loc_by_installing_you_agree:'En installant cette application, vous acceptez les ',
    loc_terms_of_use:'conditions d&#39;utilisations',
    loc_special_offer:'Offre sp&eacute;ciale. T&eacute;l&eacute;chargez-le gratuitement.',
    loc_search_from_any_page:'Cherchez avec Google depuis n&#39;importe quelle page Web.',
    loc_block_popups:'Bloquez les pop-up intempestifs.',
    loc_automatically_fill_out_forms:'Remplissez automatiquement les formulaires de commandes pour simplifier vos achats en ligne.',
    loc_include_toolbar:'Retrouvez gratuitement la barre d&#39;outils Google pour Internet Explorer.',
    loc_recommended:'(Recommand&eacute;)',
    loc_next:'Suivant',
    loc_opencandy_terms1:'Si cette offre vous convient, cliquez sur Suivant pour accepter le&nbsp;',
    loc_opencandy_terms2:'Contrat de licence de l\'utilisateur final OpenCandy',
    loc_opencandy_terms3:'',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula-fr.html',
    loc_opencandy_open_text:'Profitez &eacute;galement de cette offre gratuitement. Veuillez choisir si oui ou non vous souhaitez proc&eacute;der &agrave; l\'installation, puis cliquez ci-dessous pour commencer &agrave; jouer.',
    loc_opencandy_installed:'Success! Your game was installed!',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'En installant ces applications, vous acceptez les ',
    loc_by_installing_you_agree_chromeGTB2:'.',
    loc_by_installing_you_agree_chromeGTBlink:'Conditions d\'utilisation de Google',
    //for links
    loc_privacy:'confidentialite',
    loc_terms:'conditions-d-utilisation',
    loc_game_is_installing_title:'Jeu en cours d\'installation',
    loc_game_is_installing_text:'Attendez s\'il vous pla&icirc;t '
  },
  it: {
    loc_thank_you_for_choosing:"Grazie per aver scelto di installare",
    loc_step:'Step&nbsp;',
    loc_of:'&nbsp;di&nbsp;',
    loc_setup_options:"Opzioni per linstallazione",
    loc_choose_the_folder:"Scegli la cartella nella quale desideri installare il gioco. Si consiglia di utilizzare il percorso preimpostato. ",
    loc_choose_folder:'Scegli cartella',
    loc_bookmark_games_to_my_browser:"Salva GameHouse come sito preferito/segnalibro ",
    loc_place_a_short_on_desktop:'Crea un collegamento sul desktop per ogni gioco scaricato e installato',
    loc_agreement:'Accettazione',
    loc_if_you_agree:'Se accetti le ',
    loc_terms_of_service:'condizioni del servizio',
    loc_and:'&nbsp;e le ',
    loc_privacy_policy:'norme sulla riservatezza',
    loc_click_i_agree:', clicca su accetto per proseguire.',
    loc_i_agree:'accetto',
    loc_your_game_is_downloading:'Il download &egrave; in corso...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game.',
    loc_total_download:'Dimensione complessiva:',
    loc_download_complete:'Download terminato!',
    loc_please_wait_while_launch:'Attendi: il gioco sta per essere avviato',
    //google slides
    loc_free:'Gratuito ',
    loc_new_way_to_get_online:'GameHouse ti consiglia Google Chrome per una navigazione pi&ugrave; veloce.',
    loc_faster_access:'Accesso pi&ugrave; rapido ai tuoi siti preferiti',
    loc_search_in_address_bar:'Ricerca di Google integrata nella barra degli indirizzi',
    loc_stable_secure:'Stabile e sicuro',
    loc_include_chrome:'Include Google Chrome e ',
    loc_include_chrome2:'.',
    loc_default_chrome:'Imposta Google Chrome come browser predefinito',
    loc_by_installing_you_agree_chrome:'Installando questa applicazione accetti le ',
    loc_by_installing_you_agree_chrome2:'&nbsp;di Google Chrome.',
    loc_and_chrome:'&nbsp;e le ',
    loc_by_installing_you_agree:'Installando questa applicazione accetti le ',
    loc_terms_of_use:'condizioni d&#39;uso',
    loc_special_offer:'Offerta speciale. Ottienilo gratuitamente.',
    loc_search_from_any_page:'Cerca in Google da qualsiasi pagina Web',
    loc_block_popups:'Blocca le fastidiose finestre pop-up',
    loc_automatically_fill_out_forms:'Riempi automaticamente i formulari per acquisti online pi&ugrave; veloci',
    loc_include_toolbar:'Includi la barra degli strumenti Google gratuita per Internet Explorer',
    loc_recommended:'(Consigliato)',
    loc_next:'Prossimo',
    loc_opencandy_terms1:'Se si accetta questa offerta, facendo clic su Avanti si accetta il&nbsp;',
    loc_opencandy_terms2:'Contratto di licenza utente finale OpenCandy',
    loc_opencandy_terms3:'',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula-it.html',
    loc_opencandy_open_text:'Ecco un\'altra offerta gratis per te. Scegli se desideri installarla o meno, quindi fai clic sotto per avviare il gioco.',
    loc_opencandy_installed:'Success! Your game was installed!',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'Installando queste applicazioni, accetterai i ',
    loc_by_installing_you_agree_chromeGTB2:'.',
    loc_by_installing_you_agree_chromeGTBlink:'Termini di servizio di Google',
    //for links
    loc_privacy:'norme-sulla-riservatezza',
    loc_terms:'condizione-del-servizio',
    loc_game_is_installing_title:'Installazione gioco in corso',
    loc_game_is_installing_text:'Attendere'
  },
  sv: {
    loc_thank_you_for_choosing:"Tack f&ouml;r att du v&auml;ljer att installera",
    loc_step:'Steg&nbsp;',
    loc_of:'&nbsp;av&nbsp;',
    loc_setup_options:"Installationsalternativ",
    loc_choose_the_folder:"V&auml;lj den mapp som du vill installera ditt spel i. Vi rekommenderar att du v&auml;ljer den redan utsedda mappen.",
    loc_choose_folder:'vlj mapp',
    loc_bookmark_games_to_my_browser:"L&auml;gg till GameHouse Games som bokm&auml;rke bland mina favoriter",
    loc_place_a_short_on_desktop:'L&auml;gg en genv&auml;g p&aring; mitt skrivbord till varje spel jag laddar ned och installerar',
    loc_agreement:'&ouml;verenskommelse',
    loc_if_you_agree:'Om du godk&auml;nner ',
    loc_terms_of_service:'anv&auml;ndarvillkor',
    loc_and:'&nbsp;och ',
    loc_privacy_policy:'Sekretesspolicy',
    loc_click_i_agree:', klicka p&aring; jag godk&auml;nner f&ouml;r att forts&auml;tta.',
    loc_i_agree:'jag godk&auml;nner',
    loc_your_game_is_downloading:'Ditt spel laddas ned...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game.',
    loc_total_download:'Totalt nedladdat:',
    loc_download_complete:'Nedladdningen klar!',
    loc_please_wait_while_launch:'Var god v&auml;nta medan ditt spel startas',
    //google slides
    loc_free:'Gratis ',
    loc_new_way_to_get_online:'GameHouse rekommenderar Google Chrome, ett snabbare s&auml;tt att s&ouml;ka p&aring; internet.',
    loc_faster_access:'Snabbare tillg&aring;ng till dina favoritsidor',
    loc_search_in_address_bar:'Google Search inbyggd i adresslisten',
    loc_stable_secure:'Stabilt och s&auml;kert',
    loc_include_chrome:'Inkludera Google Chrome, tillsammans med ',
    loc_include_chrome2:'.',
    loc_default_chrome:'G&ouml;r Google Chrome till min standardwebbl&auml;sare.',
    loc_by_installing_you_agree_chrome:'Genom att installera detta program godk&auml;nner du Google Chromes ',
    loc_by_installing_you_agree_chrome2:'.',
    loc_and_chrome:'&nbsp;och ',
    loc_by_installing_you_agree:'Genom att installera detta program godk&auml;nner du ',
    loc_terms_of_use:'anv&auml;ndarvillkor',
    loc_special_offer:'Specialerbjudande. F&aring; det gratis.',
    loc_search_from_any_page:'S&ouml;k med Google fr&aring;n alla websidor',
    loc_block_popups:'Blockera irriterande pop-ups',
    loc_automatically_fill_out_forms:'Fyll i formul&auml;r automatiskt f&ouml;r snabbare online-shopping',
    loc_include_toolbar:'Inkludera gratis Google Toolbar till Internet Explorer',
    loc_recommended:'(Rekommenderat)',
    loc_next:'N&auml;sta',
    loc_opencandy_terms1:'Om du godk&auml;nde det h&auml;r erbjudandet genom att klicka p&aring; N&auml;sta, samtycker du till&nbsp;',
    loc_opencandy_terms2:'OpenCandy Licensavtal f&ouml;r slutanv&auml;ndare',
    loc_opencandy_terms3:'',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula-sv.html',
    loc_opencandy_open_text:'Vi har &auml;ven detta gratiserbjudande tillg&auml;ngligt. V&auml;lj om du vill installera eller inte och klicka sedan nedan f&ouml;r att starta ditt spel.',
    loc_opencandy_installed:'Success! Your game was installed!',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'Genom att installera dessa program godk&auml;nner du ',
    loc_by_installing_you_agree_chromeGTB2:'.',
    loc_by_installing_you_agree_chromeGTBlink:'Googles serviceavtal',
    //for links
    loc_privacy:'integritetspolicy',
    loc_terms:'villkor-vor-tjansten',
    loc_game_is_installing_title:'Installerar spel',
    loc_game_is_installing_text:'V&auml;nligen v&auml;nta '
  },
  nl: {
    loc_thank_you_for_choosing:"Bedankt voor het installeren van",
    loc_step:'Stap&nbsp;',
    loc_of:'&nbsp;van&nbsp;',
    loc_setup_options:"Installatieopties",
    loc_choose_the_folder:"Kies de map waarin je je spel wilt installeren. We adviseren je de reeds aangegeven map te kiezen.",
    loc_choose_folder:'kies map',
    loc_bookmark_games_to_my_browser:"Voeg GameHouse Games toe aan mijn favorieten",
    loc_place_a_short_on_desktop:'Plaats een snelkoppeling op mijn bureaublad voor elk spel dat ik download en installeer',
    loc_agreement:'Akkoord',
    loc_if_you_agree:'Als je akkoord gaat met de ',
    loc_terms_of_service:'Servicevoorwaarden',
    loc_and:'&nbsp;en ons ',
    loc_privacy_policy:'Privacybeleid',
    loc_click_i_agree:', klik dan op ik ga akkoord om verder te gaan.',
    loc_i_agree:'ik ga akkoord',
    loc_your_game_is_downloading:'Je spel is bezig met downloaden...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game.',
    loc_total_download:'Totale download: ',
    loc_download_complete:'Download voltooid!',
    loc_please_wait_while_launch:'Wacht tot het spel start',
    //google slides
    loc_free:'Gratis ',
    loc_new_way_to_get_online:'GameHouse adviseert Google Chrome, een snellere manier om op het web te surfen.',
    loc_faster_access:'Supersnel toegang tot je favoriete websites',
    loc_search_in_address_bar:'De adresbalk functioneert ook als Google-zoekvak',
    loc_stable_secure:'Stabiel en veilig',
    loc_include_chrome:'Installeer Google Chrome, samen met ',
    loc_include_chrome2:'.',
    loc_default_chrome:'Stel Google Chrome in als mijn standaardbrowser.',
    loc_by_installing_you_agree_chrome:'Door deze applicatie te installeren ga je akkoord met de ',
    loc_by_installing_you_agree_chrome2:'.',
    loc_and_chrome:'&nbsp;van Google Chrome en ons ',
    loc_by_installing_you_agree:'Door deze applicatie te installeren ga je akkoord met de gebruiksvoorwaarden van ',
    loc_terms_of_use:'Servicevoorwaarden',
    loc_special_offer:'Speciale aanbieding. Gratis.',
    loc_search_from_any_page:'Zoek met Google vanaf elke webpagina',
    loc_block_popups:'Blokkeer irritante pop-ups',
    loc_automatically_fill_out_forms:'Vul formulieren automatisch is en shop nog sneller online',
    loc_include_toolbar:'Inclusief de gratis Google Toolbar voor Internet Explorer',
    loc_recommended:'(Aanbevolen)',
    loc_next:'Volgende',
    loc_opencandy_terms1:'Als u dit aanbod hebt geaccepteerd door te klikken op Volgende, dan gaat u akkoord met de&nbsp;',
    loc_opencandy_terms2:'OpenCandy licentieovereenkomst voor eindgebruikers',
    loc_opencandy_terms3:'',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula-nl.html',
    loc_opencandy_open_text:'We hebben ook dit gratis aanbod voor je. Selecteer of je het wilt installeren of niet, en klik hieronder om je spel te starten.',
    loc_opencandy_installed:'Succesvolle installatie van ',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'Door deze applicaties te installeren, ga je akkoord met de ',
    loc_by_installing_you_agree_chromeGTB2:'.',
    loc_by_installing_you_agree_chromeGTBlink:'Servicevoorwaarden van Google',
    //for links
    loc_privacy:'privacy',
    loc_terms:'voorwaarden',
    loc_game_is_installing_title:'Bezig met installeren',
    loc_game_is_installing_text:'Even geduld alsjeblieft '
  },
  pt: {
    loc_thank_you_for_choosing:"Obrigado por instalar o jogo",
    loc_step:'Etapa&nbsp;',
    loc_of:'&nbsp;de&nbsp;',
    loc_setup_options:"Op&ccedil;&otilde;es de instala&ccedil;&atilde;o",
    loc_choose_the_folder:"Escolha a pasta em que gostaria de instalar o jogo. Recomendamos que use a pasta j&aacute; especificada.",
    loc_choose_folder:'escolher pasta',
    loc_bookmark_games_to_my_browser:"Adicionar o site do GameHouse aos meus favoritos ",
    loc_place_a_short_on_desktop:'Criar um atalho na minha &aacute;rea de trabalho para todos os jogos que eu baixar e instalar ',
    loc_agreement:'Acordo',
    loc_if_you_agree:'Se voc&ecirc; concorda com os ',
    loc_terms_of_service:'Termos de Servi&ccedil;o',
    loc_and:'&nbsp;e com a ',
    loc_privacy_policy:'Pol&iacute;tica de Privacidade',
    loc_click_i_agree:', clique em concordo para prosseguir.',
    loc_i_agree:'concordo',
    loc_your_game_is_downloading:'Seu jogo est&aacute; sendo baixado...',
    loc_clicking_ad: 'Clicking an ad will open a new window and not interrupt your game.',
    loc_total_download:'Volume total de download: ',
    loc_download_complete:'Download conclu&iacute;do!',
    loc_please_wait_while_launch:'Aguarde enquanto seu jogo &eacute; iniciado',
    //google slides
    loc_free:'Gr&aacute;tis ',
    loc_new_way_to_get_online:'GameHouse recomenda o Google Chrome, uma maneira mais r&aacute;pida de navegar na web.',
    loc_faster_access:'Acesso mais r&aacute;pido a seus sites favoritos',
    loc_search_in_address_bar:'Google Search inclu&iacute;do na barra de endere&ccedil;o',
    loc_stable_secure:'Est&aacute;vel e Seguro',
    loc_include_chrome:'Inclui o Google Chrome, juntamente com ',
    loc_include_chrome2:'.',
    loc_default_chrome:'Fazer do Google Chrome meu navegador-padr&atilde;o',
    loc_by_installing_you_agree_chrome:'Ao instalar este aplicativo, voc&ecirc; concorda com o Google Chrome ',
    loc_by_installing_you_agree_chrome2:'.',
    loc_and_chrome:'&nbsp;e com a ',
    loc_by_installing_you_agree:'Ao instalar este aplicativo, voc&ecirc; concorda com o ',
    loc_terms_of_use:'Termos de Uso',
    loc_special_offer:'Oferta especial. Gr&aacute;tis.',
    loc_search_from_any_page:'Realize buscas no Google a partir de qualquer p&aacute;gina.',
    loc_block_popups:'Bloqueie pop-ups irritantes',
    loc_automatically_fill_out_forms:'Preencha formul&aacute;rios automaticamente para agilizar suas compras on-line',
    loc_include_toolbar:'Inclua a Barra gratuita do Google para o Internet Explorer',
    loc_recommended:'(Recomendado)',
    loc_next:'Seguinte',
    loc_opencandy_terms1:'Se voc&ecirc; tiver aceitado essa oferta, clique em Avan&ccedil;ar para concordar com o&nbsp;',
    loc_opencandy_terms2:'Contrato de Licen&ccedil;a de Usu&aacute;rio Final da OpenCandy.',
    loc_opencandy_terms3:'',
    loc_opencandy_eulaURL:'http://www.opencandy.com/eulas/sneula-pt.html',
    loc_opencandy_open_text:'N&oacute;s temos ainda esta oferta dispon&iacute;vel de gra&ccedil;a. Selecione se deseja instalar e em seguida clique embaixo para come&ccedil;ar seu jogo.',
    loc_opencandy_installed:'Success! Your game was installed!',
    loc_opencandy_start_game:'Start your game',
    loc_by_installing_you_agree_chromeGTB:'Ao instalar estes aplicativos, voc&ecirc; concorda com os ',
    loc_by_installing_you_agree_chromeGTB2:'.',
    loc_by_installing_you_agree_chromeGTBlink:'Termos de Servi&ccedil;o do Google',
    //for links
    loc_privacy:'politica-de-privacidade',
    loc_terms:'termos-de-servico',
    loc_game_is_installing_title:'Instalando o jogo',
    loc_game_is_installing_text:'Aguarde '
  }
};
