copy /y "ra1_games_demo.htm" "quicklaunch_plus_rawk_ra1_direct_dl.htm"
copy /y "ra1_games_demo.htm" "rawk_ra1_direct_dl.htm"
copy /y "ra1_games_full.htm" "rawk_ra1full_direct_dl.htm"
copy /y "ra2_games_demo_gh.htm" "rawk_rg2gh_direct_dl.htm"
copy /y "ra2_games_demo_ra.htm" "rawk_rg2ra_direct_dl.htm"
copy /y "ra3_games_demo.htm" "rawk_rg3_direct_dl.htm"
copy /y "ra4_games_demo.htm" "rawk_rg4_direct_dl.htm"
del "ra1_games_demo.htm"
del "ra1_games_full.htm"
del "ra1_games_mez.htm"
del "ra1_games_rgp.htm"
del "ra2_games_demo_gh.htm"
del "ra2_games_demo_ra.htm"
del "ra3_games_demo.htm"
del "ra3_games_mac.htm"
del "ra3_games_unlimited.htm"
del "ra3_stub_info_web_links.htm"
del "ra3_games_episodic_check.htm"
del "ra4_games_demo.htm"
del "ra1_games_demo_multilang.htm"
del "ra4_games_demo-installers.htm"
