@echo off
title RealArcade Wrapper Killer v%rawkver%    (.-+'~^-+ Junk Files Cleaner CLI +-^~`+-.)     [...cRypTiCwaRe 2o2o...]


cls

::-----------------------------------------------------------------------------------
:: Clean for CLI [20200509]
::-----------------------------------------------------------------------------------
if exist "ami-launch-fix-32.reg" del /f /q "ami-launch-fix-32.reg"
if exist "ami-launch-fix-64.reg" del /f /q "ami-launch-fix-64.reg"
if exist "ami-launch-fix-remove.reg" del /f /q "ami-launch-fix-remove.reg"
if exist "ami-remove-all.reg" del /f /q "ami-remove-all.reg"
if exist "ami-remove-licensing.reg" del /f /q "ami-remove-licensing.reg"
if exist "cliptemp.txt" del /f /q "cliptemp.txt"
if exist "core_advanced_load_options.cmd" del /f /q "core_advanced_load_options.cmd"
if exist "core_am_instant_server.cmd" del /f /q "core_am_instant_server.cmd"
if exist "core_autolaunch.cmd" del /f /q "core_autolaunch.cmd"
if exist "core_backup.cmd" del /f /q "core_backup.cmd"
if exist "core_cheats.cmd" del /f /q "core_cheats.cmd"
if exist "core_check_dependencies.cmd" del /f /q "core_check_dependencies.cmd"
if exist "core_check_exit_status.cmd" del /f /q "core_check_exit_status.cmd"
if exist "core_check_ini_ver.cmd" del /f /q "core_check_ini_ver.cmd"
if exist "core_check_local_rawk.cmd" del /f /q "core_check_local_rawk.cmd"
if exist "core_check_non_rgs.cmd" del /f /q "core_check_non_rgs.cmd"
if exist "core_clean_exe.cmd" del /f /q "core_clean_exe.cmd"
if exist "core_clean_gh.cmd" del /f /q "core_clean_gh.cmd"
if exist "core_clean_ini.cmd" del /f /q "core_clean_ini.cmd"
if exist "core_clean_main.cmd" del /f /q "core_clean_main.cmd"
if exist "core_clean_pre.cmd" del /f /q "core_clean_pre.cmd"
if exist "core_clean_reg_hacks.cmd" del /f /q "core_clean_reg_hacks.cmd"
if exist "core_clean_zy.cmd" del /f /q "core_clean_zy.cmd"
if exist "core_clear_cache.cmd" del /f /q "core_clear_cache.cmd"
if exist "core_config_ra_player.cmd" del /f /q "core_config_ra_player.cmd"
if exist "core_debug.cmd" del /f /q "core_debug.cmd"
if exist "core_delete_backups.cmd" del /f /q "core_delete_backups.cmd"
if exist "core_demo_type_check.cmd" del /f /q "core_demo_type_check.cmd"
if exist "core_demo_type_override.cmd" del /f /q "core_demo_type_override.cmd"
if exist "core_disable_old_reg_hacks.cmd" del /f /q "core_disable_old_reg_hacks.cmd"
if exist "core_dlc.cmd" del /f /q "core_dlc.cmd"
if exist "core_dmg_loader.cmd" del /f /q "core_dmg_loader.cmd"
if exist "core_dupe_check.cmd" del /f /q "core_dupe_check.cmd"
if exist "core_errorhandling.cmd" del /f /q "core_errorhandling.cmd"
if exist "core_file_rename.cmd" del /f /q "core_file_rename.cmd"
if exist "core_gamehouse_hotkey.cmd" del /f /q "core_gamehouse_hotkey.cmd"
if exist "core_gamehouse_main.cmd" del /f /q "core_gamehouse_main.cmd"
if exist "core_gamehouse_override.cmd" del /f /q "core_gamehouse_override.cmd"
if exist "core_game_patch.cmd" del /f /q "core_game_patch.cmd"
if exist "core_game_unpacked_ok.cmd" del /f /q "core_game_unpacked_ok.cmd"
if exist "core_get_demo_type.cmd" del /f /q "core_get_demo_type.cmd"
if exist "core_get_stats.cmd" del /f /q "core_get_stats.cmd"
if exist "core_ghx_install.cmd" del /f /q "core_ghx_install.cmd"
if exist "core_ghx_reset.cmd" del /f /q "core_ghx_reset.cmd"
if exist "core_gh_web_scraper.cmd" del /f /q "core_gh_web_scraper.cmd"
if exist "core_handler.cmd" del /f /q "core_handler.cmd"
if exist "core_hotkey.cmd" del /f /q "core_hotkey.cmd"
if exist "core_ini_output.cmd" del /f /q "core_ini_output.cmd"
if exist "core_invalid_folder.cmd" del /f /q "core_invalid_folder.cmd"
if exist "core_invalid_folder_gh.cmd" del /f /q "core_invalid_folder_gh.cmd"
if exist "core_invalid_folder_zylom.cmd" del /f /q "core_invalid_folder_zylom.cmd"
if exist "core_licensing_activemark.cmd" del /f /q "core_licensing_activemark.cmd"
if exist "core_licensing_gamehouse.cmd" del /f /q "core_licensing_gamehouse.cmd"
if exist "core_licensing_main.cmd" del /f /q "core_licensing_main.cmd"
if exist "core_licensing_realarcade.cmd" del /f /q "core_licensing_realarcade.cmd"
if exist "core_licensing_zylom.cmd" del /f /q "core_licensing_zylom.cmd"
if exist "core_mods.cmd" del /f /q "core_mods.cmd"
if exist "core_multicmp.cmd" del /f /q "core_multicmp.cmd"
if exist "core_multiple_exe_check.cmd" del /f /q "core_multiple_exe_check.cmd"
if exist "core_no_game_found.cmd" del /f /q "core_no_game_found.cmd"
if exist "core_no_var_fix.cmd" del /f /q "core_no_var_fix.cmd"
if exist "core_ogm_service.cmd" del /f /q "core_ogm_service.cmd"
if exist "core_override.cmd" del /f /q "core_override.cmd"
if exist "core_patch_demo1.cmd" del /f /q "core_patch_demo1.cmd"
if exist "core_patch_demo3.cmd" del /f /q "core_patch_demo3.cmd"
if exist "core_patch_demo3a.cmd" del /f /q "core_patch_demo3a.cmd"
if exist "core_patch_demo4.cmd" del /f /q "core_patch_demo4.cmd"
if exist "core_patch_demo4a.cmd" del /f /q "core_patch_demo4a.cmd"
if exist "core_patch_demoGH.cmd" del /f /q "core_patch_demoGH.cmd"
if exist "core_patch_demoZY.cmd" del /f /q "core_patch_demoZY.cmd"
if exist "core_patch_ra_db.cmd" del /f /q "core_patch_ra_db.cmd"
if exist "core_pdf_fix.cmd" del /f /q "core_pdf_fix.cmd"
if exist "core_rawk_cleanup_loader.cmd" del /f /q "core_rawk_cleanup_loader.cmd"
if exist "core_rawk_cleanup_root.cmd" del /f /q "core_rawk_cleanup_root.cmd"
if exist "core_rawk_unpack.cmd" del /f /q "core_rawk_unpack.cmd"
if exist "core_reg_check.cmd" del /f /q "core_reg_check.cmd"
if exist "core_reg_set.cmd" del /f /q "core_reg_set.cmd"
if exist "core_restore.cmd" del /f /q "core_restore.cmd"
if exist "core_rfs_loader.cmd" del /f /q "core_rfs_loader.cmd"
if exist "core_rfs_stub_info.cmd" del /f /q "core_rfs_stub_info.cmd"
if exist "core_rga_download.cmd" del /f /q "core_rga_download.cmd"
if exist "core_rga_stub_info.cmd" del /f /q "core_rga_stub_info.cmd"
if exist "core_rgs_game_patcher.cmd" del /f /q "core_rgs_game_patcher.cmd"
if exist "core_rgs_loader.cmd" del /f /q "core_rgs_loader.cmd"
if exist "core_rgs_pre_release.cmd" del /f /q "core_rgs_pre_release.cmd"
if exist "core_rgs_unlock_license.cmd" del /f /q "core_rgs_unlock_license.cmd"
if exist "core_rnarcade_spoofer.cmd" del /f /q "core_rnarcade_spoofer.cmd"
if exist "core_set_breakpoint.cmd" del /f /q "core_set_breakpoint.cmd"
if exist "core_set_def_ini.cmd" del /f /q "core_set_def_ini.cmd"
if exist "core_set_global.cmd" del /f /q "core_set_global.cmd"
if exist "core_shortcut_demo1.cmd" del /f /q "core_shortcut_demo1.cmd"
if exist "core_shortcut_demo1a.cmd" del /f /q "core_shortcut_demo1a.cmd"
if exist "core_shortcut_demo2.cmd" del /f /q "core_shortcut_demo2.cmd"
if exist "core_shortcut_demo3.cmd" del /f /q "core_shortcut_demo3.cmd"
if exist "core_shortcut_demo4.cmd" del /f /q "core_shortcut_demo4.cmd"
if exist "core_shortcut_demo5.cmd" del /f /q "core_shortcut_demo5.cmd"
if exist "core_shortcut_demo6.cmd" del /f /q "core_shortcut_demo6.cmd"
if exist "core_shortcut_demoGH.cmd" del /f /q "core_shortcut_demoGH.cmd"
if exist "core_shortcut_demoZY.cmd" del /f /q "core_shortcut_demoZY.cmd"
if exist "core_shortcut_manual.cmd" del /f /q "core_shortcut_manual.cmd"
if exist "core_show_stats.cmd" del /f /q "core_show_stats.cmd"
if exist "core_sonic_multi_fix.cmd" del /f /q "core_sonic_multi_fix.cmd"
if exist "core_stub_creator.cmd" del /f /q "core_stub_creator.cmd"
if exist "core_unsupported.cmd" del /f /q "core_unsupported.cmd"
if exist "core_update.cmd" del /f /q "core_update.cmd"
if exist "core_zylom_hotkey.cmd" del /f /q "core_zylom_hotkey.cmd"
if exist "core_zylom_main.cmd" del /f /q "core_zylom_main.cmd"
if exist "core_zylom_override.cmd" del /f /q "core_zylom_override.cmd"
if exist "demo1.cmd" del /f /q "demo1.cmd"
if exist "demo1a.cmd" del /f /q "demo1a.cmd"
if exist "demo2.cmd" del /f /q "demo2.cmd"
if exist "demo3.cmd" del /f /q "demo3.cmd"
if exist "demo3a.cmd" del /f /q "demo3a.cmd"
if exist "demo4.cmd" del /f /q "demo4.cmd"
if exist "demo4a.cmd" del /f /q "demo4a.cmd"
if exist "demo5.cmd" del /f /q "demo5.cmd"
if exist "demo6.cmd" del /f /q "demo6.cmd"
if exist "demoGH.cmd" del /f /q "demoGH.cmd"
if exist "demoM.cmd" del /f /q "demoM.cmd"
if exist "demoZY.cmd" del /f /q "demoZY.cmd"
if exist "filesize.vbs" del /f /q "filesize.vbs"
if exist "fix1.tmp" del /f /q "fix1.tmp"
if exist "fix2.tmp" del /f /q "fix2.tmp"
if exist "fix3.tmp" del /f /q "fix3.tmp"
if exist "RAunWrap.cmd" del /f /q "RAunWrap.cmd"
if exist "rawk_licensekeys.reg" del /f /q "rawk_licensekeys.reg"
if exist "rawk_prefs.reg" del /f /q "rawk_prefs.reg"
if exist "rawk_reset.reg" del /f /q "rawk_reset.reg"
if exist "rga_stub_bypass.reg" del /f /q "rga_stub_bypass.reg"
if exist "rga_stub_remove.reg" del /f /q "rga_stub_remove.reg"
if exist "rgs_open_default.reg" del /f /q "rgs_open_default.reg"
if exist "stub-chunk1.bin" del /f /q "stub-chunk1.bin"
if exist "stub-chunk2-installation-id.bin" del /f /q "stub-chunk2-installation-id.bin"
if exist "stub-chunk3-offering.bin" del /f /q "stub-chunk3-offering.bin"
if exist "stub-chunk4-filler.bin" del /f /q "stub-chunk4-filler.bin"
if exist "stub-chunk5-language-country.bin" del /f /q "stub-chunk5-language-country.bin"
if exist "stub-chunk6.bin" del /f /q "stub-chunk6.bin"


:: Remove yourself
if exist "core_clean_cli.cmd" del /f /q "core_clean_cli.cmd"

:end

if %testmode%==1 (
	echo [core_clean_cli : finished]
	pause>nul
)
