@echo off
title RealArcade Wrapper Killer v%rawkver%    (.-+'~^-+ RAWK Cleanup +-^~`+-.)     [...cRypTiCwaRe 2o13...]


::-----------------------------------------------------------------------------------------
:: Cleaning up RAWK after game install and RAWK launch/unpack finished
::-----------------------------------------------------------------------------------------

set gamesroot=C:\My Games


rd /s /q "cheats"
rd /s /q "patches"

del /s /q /f "cliptemp.txt"
del /s /q /f "core_advanced_load_options.bat"
del /s /q /f "core_autolaunch.bat"
del /s /q /f "core_backup.bat"
del /s /q /f "core_cheats.bat"
del /s /q /f "core_check_exit_status.bat"
del /s /q /f "core_check_ini_ver.bat"
del /s /q /f "core_check_local_rawk.bat"
del /s /q /f "core_check_non_rgs.bat"
del /s /q /f "core_clean_exe.bat"
del /s /q /f "core_clean_gh.bat"
del /s /q /f "core_clean_zy.bat"
del /s /q /f "core_clean_ini.bat"
del /s /q /f "core_clean_main.bat"
del /s /q /f "core_clean_pre.bat"
del /s /q /f "core_clear_cache.bat"
del /s /q /f "core_config_ra_player.bat"
del /s /q /f "core_debug.bat"
del /s /q /f "core_delete_backups.bat"
del /s /q /f "core_demo_type_check.bat"
del /s /q /f "core_demo_type_override.bat"
del /s /q /f "core_disable_old_reg_hacks.bat"
del /s /q /f "core_dlc.bat"
del /s /q /f "core_dupe_check.bat"
del /s /q /f "core_errorhandling.bat"
del /s /q /f "core_file_rename.bat"
del /s /q /f "core_gamehouse_hotkey.bat"
del /s /q /f "core_gamehouse_main.bat"
del /s /q /f "core_gamehouse_override.bat"
del /s /q /f "core_game_patch.bat"
del /s /q /f "core_game_unpacked_ok.bat"
del /s /q /f "core_get_demo_type.bat"
del /s /q /f "core_get_stats.bat"
del /s /q /f "core_ghx_install.cmd"
del /s /q /f "core_ghx_reset.cmd"
del /s /q /f "core_handler.bat"
del /s /q /f "core_hotkey.bat"
del /s /q /f "core_ini_output.bat"
del /s /q /f "core_invalid_folder.bat"
del /s /q /f "core_invalid_folder_gh.bat"
del /s /q /f "core_invalid_folder_zylom.bat"
del /s /q /f "core_licensing_activemark.bat"
del /s /q /f "core_licensing_gamehouse.bat"
del /s /q /f "core_licensing_main.bat"
del /s /q /f "core_licensing_realarcade.bat"
del /s /q /f "core_licensing_zylom.bat"
del /s /q /f "core_mods.bat"
del /s /q /f "core_multicmp.bat"
del /s /q /f "core_multiple_exe_check.bat"
del /s /q /f "core_no_game_found.bat"
del /s /q /f "core_no_var_fix.bat"
del /s /q /f "core_override.bat"
del /s /q /f "core_patch_demo1.bat"
del /s /q /f "core_patch_demo3.bat"
del /s /q /f "core_patch_demo3a.bat"
del /s /q /f "core_patch_demo4.bat"
del /s /q /f "core_patch_demo4a.bat"
del /s /q /f "core_patch_demoGH.bat"
del /s /q /f "core_patch_demoZY.bat"
del /s /q /f "core_patch_ra_db.bat"
del /s /q /f "core_pdf_fix.bat"
del /s /q /f "core_rawk_unpack.bat"
del /s /q /f "core_reg_check.bat"
del /s /q /f "core_reg_set.bat"
del /s /q /f "core_restore.bat"
del /s /q /f "core_rga_download.bat"
del /s /q /f "core_rga_stub_creator.bat"
del /s /q /f "core_rga_stub_info.bat"
del /s /q /f "core_rgs_loader.bat"
del /s /q /f "core_rgs_pre_release.bat"
del /s /q /f "core_rgs_unlock_license.bat"
del /s /q /f "core_rnarcade_spoofer.bat"
del /s /q /f "core_set_breakpoint.bat"
del /s /q /f "core_set_def_ini.bat"
del /s /q /f "core_set_global.bat"
del /s /q /f "core_shortcut_demo1.bat"
del /s /q /f "core_shortcut_demo1a.bat"
del /s /q /f "core_shortcut_demo2.bat"
del /s /q /f "core_shortcut_demo3.bat"
del /s /q /f "core_shortcut_demo4.bat"
del /s /q /f "core_shortcut_demo5.bat"
del /s /q /f "core_shortcut_demo6.bat"
del /s /q /f "core_shortcut_demoGH.bat"
del /s /q /f "core_shortcut_demoZY.bat"
del /s /q /f "core_shortcut_manual.bat"
del /s /q /f "core_show_stats.bat"
del /s /q /f "core_sonic_multi_fix.bat"
del /s /q /f "core_unsupported.bat"
del /s /q /f "core_update.bat"
del /s /q /f "core_zylom_hotkey.bat"
del /s /q /f "core_zylom_main.bat"
del /s /q /f "core_zylom_override.bat"
del /s /q /f "demo1.bat"
del /s /q /f "demo1a.bat"
del /s /q /f "demo2.bat"
del /s /q /f "demo3.bat"
del /s /q /f "demo3a.bat"
del /s /q /f "demo4.bat"
del /s /q /f "demo4a.bat"
del /s /q /f "demo5.bat"
del /s /q /f "demo6.bat"
del /s /q /f "demoGH.bat"
del /s /q /f "demoZY.bat"
del /s /q /f "demoM.bat"
del /s /q /f "filesize.vbs"
del /s /q /f "fix1.tmp"
del /s /q /f "fix2.tmp"
del /s /q /f "fix3.tmp"
del /s /q /f "gameInitializer.rgi"
del /s /q /f "gameInstall.rgi"
del /s /q /f "launch.ini"
del /s /q /f "RAunWrap.bat"
del /s /q /f "rawk_licensekeys.reg"
del /s /q /f "rawk_prefs.reg"
del /s /q /f "rawk_reset.reg"
del /s /q /f "rgastub.bin"
del /s /q /f "rga_stub_bypass.reg"
del /s /q /f "rga_stub_remove.reg"
del /s /q /f "rgs_open_default.reg"


del /s /q /f ".ini"
del /s /q /f "ghdbtemp.bat"
del /s /q /f "zydbtemp.bat"

del /s /q /f "ghdb_core_installed_ver.bat"
del /s /q /f "zydb_core_installed_ver.bat"
del /s /q /f "ghdb_core_available_ver.bat"
del /s /q /f "zydb_core_available_ver.bat"
del /s /q /f "ghdb_core_running_ver.bat"
del /s /q /f "zydb_core_running_ver.bat"

del /s /q /f "core_rawk_cleanup_loader.bat"
del /s /q /f "core_rawk_cleanup_root.bat"

:end
