@echo off
title RealArcade Wrapper Killer v%rawkver%    (.-+'~^-+ RAWK Cleanup +-^~`+-.)     [...cRypTiCwaRe 2o16...]


::-----------------------------------------------------------------------------------------
:: Cleaning up RAWK after game install and RAWK launch/unpack finished
::-----------------------------------------------------------------------------------------

set gamesroot=C:\My Games


rd /s /q "%gamesroot%\%GameName%\cheats"
rd /s /q "%gamesroot%\%GameName%\patches"

del /s /q /f "%gamesroot%\%GameName%\cliptemp.txt"
del /s /q /f "%gamesroot%\%GameName%\core_advanced_load_options.bat"
del /s /q /f "%gamesroot%\%GameName%\core_autolaunch.bat"
del /s /q /f "%gamesroot%\%GameName%\core_backup.bat"
del /s /q /f "%gamesroot%\%GameName%\core_cheats.bat"
del /s /q /f "%gamesroot%\%GameName%\core_check_exit_status.bat"
del /s /q /f "%gamesroot%\%GameName%\core_check_ini_ver.bat"
del /s /q /f "%gamesroot%\%GameName%\core_check_local_rawk.bat"
del /s /q /f "%gamesroot%\%GameName%\core_check_non_rgs.bat"
del /s /q /f "%gamesroot%\%GameName%\core_clean_exe.bat"
del /s /q /f "%gamesroot%\%GameName%\core_clean_gh.bat"
del /s /q /f "%gamesroot%\%GameName%\core_clean_zy.bat"
del /s /q /f "%gamesroot%\%GameName%\core_clean_ini.bat"
del /s /q /f "%gamesroot%\%GameName%\core_clean_main.bat"
del /s /q /f "%gamesroot%\%GameName%\core_clean_pre.bat"
del /s /q /f "%gamesroot%\%GameName%\core_clear_cache.bat"
del /s /q /f "%gamesroot%\%GameName%\core_config_ra_player.bat"
del /s /q /f "%gamesroot%\%GameName%\core_debug.bat"
del /s /q /f "%gamesroot%\%GameName%\core_delete_backups.bat"
del /s /q /f "%gamesroot%\%GameName%\core_demo_type_check.bat"
del /s /q /f "%gamesroot%\%GameName%\core_demo_type_override.bat"
del /s /q /f "%gamesroot%\%GameName%\core_disable_old_reg_hacks.bat"
del /s /q /f "%gamesroot%\%GameName%\core_dlc.bat"
del /s /q /f "%gamesroot%\%GameName%\core_dupe_check.bat"
del /s /q /f "%gamesroot%\%GameName%\core_errorhandling.bat"
del /s /q /f "%gamesroot%\%GameName%\core_file_rename.bat"
del /s /q /f "%gamesroot%\%GameName%\core_gamehouse_hotkey.bat"
del /s /q /f "%gamesroot%\%GameName%\core_gamehouse_main.bat"
del /s /q /f "%gamesroot%\%GameName%\core_gamehouse_override.bat"
del /s /q /f "%gamesroot%\%GameName%\core_game_patch.bat"
del /s /q /f "%gamesroot%\%GameName%\core_game_unpacked_ok.bat"
del /s /q /f "%gamesroot%\%GameName%\core_get_demo_type.bat"
del /s /q /f "%gamesroot%\%GameName%\core_get_stats.bat"
del /s /q /f "%gamesroot%\%GameName%\core_ghx_install.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_ghx_reset.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_handler.bat"
del /s /q /f "%gamesroot%\%GameName%\core_hotkey.bat"
del /s /q /f "%gamesroot%\%GameName%\core_ini_output.bat"
del /s /q /f "%gamesroot%\%GameName%\core_invalid_folder.bat"
del /s /q /f "%gamesroot%\%GameName%\core_invalid_folder_gh.bat"
del /s /q /f "%gamesroot%\%GameName%\core_invalid_folder_zylom.bat"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_activemark.bat"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_gamehouse.bat"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_main.bat"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_realarcade.bat"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_zylom.bat"
del /s /q /f "%gamesroot%\%GameName%\core_mods.bat"
del /s /q /f "%gamesroot%\%GameName%\core_multicmp.bat"
del /s /q /f "%gamesroot%\%GameName%\core_multiple_exe_check.bat"
del /s /q /f "%gamesroot%\%GameName%\core_no_game_found.bat"
del /s /q /f "%gamesroot%\%GameName%\core_no_var_fix.bat"
del /s /q /f "%gamesroot%\%GameName%\core_override.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo1.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo3.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo3a.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo4.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo4a.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demoGH.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demoZY.bat"
del /s /q /f "%gamesroot%\%GameName%\core_patch_ra_db.bat"
del /s /q /f "%gamesroot%\%GameName%\core_pdf_fix.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rawk_unpack.bat"
del /s /q /f "%gamesroot%\%GameName%\core_reg_check.bat"
del /s /q /f "%gamesroot%\%GameName%\core_reg_set.bat"
del /s /q /f "%gamesroot%\%GameName%\core_restore.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rga_download.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rga_stub_creator.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rga_stub_info.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rgs_loader.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rgs_pre_release.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rgs_unlock_license.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rnarcade_spoofer.bat"
del /s /q /f "%gamesroot%\%GameName%\core_set_breakpoint.bat"
del /s /q /f "%gamesroot%\%GameName%\core_set_def_ini.bat"
del /s /q /f "%gamesroot%\%GameName%\core_set_global.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo1.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo1a.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo2.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo3.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo4.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo5.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo6.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demoGH.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demoZY.bat"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_manual.bat"
del /s /q /f "%gamesroot%\%GameName%\core_show_stats.bat"
del /s /q /f "%gamesroot%\%GameName%\core_sonic_multi_fix.bat"
del /s /q /f "%gamesroot%\%GameName%\core_unsupported.bat"
del /s /q /f "%gamesroot%\%GameName%\core_update.bat"
del /s /q /f "%gamesroot%\%GameName%\core_zylom_hotkey.bat"
del /s /q /f "%gamesroot%\%GameName%\core_zylom_main.bat"
del /s /q /f "%gamesroot%\%GameName%\core_zylom_override.bat"
del /s /q /f "%gamesroot%\%GameName%\demo1.bat"
del /s /q /f "%gamesroot%\%GameName%\demo1a.bat"
del /s /q /f "%gamesroot%\%GameName%\demo2.bat"
del /s /q /f "%gamesroot%\%GameName%\demo3.bat"
del /s /q /f "%gamesroot%\%GameName%\demo3a.bat"
del /s /q /f "%gamesroot%\%GameName%\demo4.bat"
del /s /q /f "%gamesroot%\%GameName%\demo4a.bat"
del /s /q /f "%gamesroot%\%GameName%\demo5.bat"
del /s /q /f "%gamesroot%\%GameName%\demo6.bat"
del /s /q /f "%gamesroot%\%GameName%\demoGH.bat"
del /s /q /f "%gamesroot%\%GameName%\demoZY.bat"
del /s /q /f "%gamesroot%\%GameName%\demoM.bat"
del /s /q /f "%gamesroot%\%GameName%\filesize.vbs"
del /s /q /f "%gamesroot%\%GameName%\fix1.tmp"
del /s /q /f "%gamesroot%\%GameName%\fix2.tmp"
del /s /q /f "%gamesroot%\%GameName%\fix3.tmp"
del /s /q /f "%gamesroot%\%GameName%\gameInitializer.rgi"
del /s /q /f "%gamesroot%\%GameName%\gameInstall.rgi"
del /s /q /f "%gamesroot%\%GameName%\launch.ini"
del /s /q /f "%gamesroot%\%GameName%\RAunWrap.bat"
del /s /q /f "%gamesroot%\%GameName%\rawk_licensekeys.reg"
del /s /q /f "%gamesroot%\%GameName%\rawk_prefs.reg"
del /s /q /f "%gamesroot%\%GameName%\rawk_reset.reg"
del /s /q /f "%gamesroot%\%GameName%\rgastub.bin"
del /s /q /f "%gamesroot%\%GameName%\rga_stub_bypass.reg"
del /s /q /f "%gamesroot%\%GameName%\rga_stub_remove.reg"
del /s /q /f "%gamesroot%\%GameName%\rgs_open_default.reg"

del /s /q /f "%gamesroot%\%GameName%\.ini"
del /s /q /f "%gamesroot%\%GameName%\ghdbtemp.bat"
del /s /q /f "%gamesroot%\%GameName%\zydbtemp.bat"

del /s /q /f "%gamesroot%\%GameName%\ghdb_core_installed_ver.bat"
del /s /q /f "%gamesroot%\%GameName%\zydb_core_installed_ver.bat"
del /s /q /f "%gamesroot%\%GameName%\ghdb_core_available_ver.bat"
del /s /q /f "%gamesroot%\%GameName%\zydb_core_available_ver.bat"
del /s /q /f "%gamesroot%\%GameName%\ghdb_core_running_ver.bat"
del /s /q /f "%gamesroot%\%GameName%\zydb_core_running_ver.bat"

del /s /q /f "%gamesroot%\%GameName%\core_rawk_cleanup_loader.bat"
del /s /q /f "%gamesroot%\%GameName%\core_rawk_cleanup_root.bat"

:end
