@echo off
title RealArcade Wrapper Killer v%rawkver%    (.-+'~^-+ RAWK Cleanup +-^~`+-.)     [...cRypTiCwaRe 2o2o...]


::-----------------------------------------------------------------------------------------
:: Cleaning up RAWK after game install and RAWK launch/unpack finished
::-----------------------------------------------------------------------------------------

set gamesroot=C:\My Games


rd /s /q "%gamesroot%\%GameName%\cheats"
rd /s /q "%gamesroot%\%GameName%\patches"
rd /s /q "%gamesroot%\%GameName%\stub"

del /s /q /f "%gamesroot%\%GameName%\cliptemp.txt"
del /s /q /f "%gamesroot%\%GameName%\core_advanced_load_options.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_autolaunch.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_backup.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_cheats.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_check_exit_status.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_check_ini_ver.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_check_local_rawk.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_check_non_rgs.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_clean_exe.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_clean_gh.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_clean_zy.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_clean_ini.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_clean_main.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_clean_pre.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_clear_cache.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_config_ra_player.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_debug.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_delete_backups.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_demo_type_check.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_demo_type_override.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_disable_old_reg_hacks.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_dlc.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_dupe_check.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_errorhandling.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_file_rename.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_gamehouse_hotkey.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_gamehouse_main.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_gamehouse_override.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_game_patch.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_game_unpacked_ok.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_get_demo_type.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_get_stats.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_ghx_install.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_ghx_reset.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_handler.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_hotkey.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_ini_output.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_invalid_folder.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_invalid_folder_gh.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_invalid_folder_zylom.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_activemark.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_gamehouse.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_main.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_realarcade.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_licensing_zylom.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_mods.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_multicmp.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_multiple_exe_check.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_no_game_found.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_no_var_fix.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_override.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo1.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo3.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo3a.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo4.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demo4a.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demoGH.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_demoZY.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_patch_ra_db.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_pdf_fix.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rawk_unpack.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_reg_check.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_reg_set.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_restore.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rga_download.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rga_stub_creator.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rga_stub_info.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rgs_loader.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rgs_pre_release.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rgs_unlock_license.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rnarcade_spoofer.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_set_breakpoint.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_set_def_ini.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_set_global.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo1.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo1a.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo2.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo3.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo4.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo5.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demo6.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demoGH.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_demoZY.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_shortcut_manual.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_show_stats.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_sonic_multi_fix.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_unsupported.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_update.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_zylom_hotkey.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_zylom_main.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_zylom_override.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo1.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo1a.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo2.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo3.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo3a.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo4.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo4a.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo5.cmd"
del /s /q /f "%gamesroot%\%GameName%\demo6.cmd"
del /s /q /f "%gamesroot%\%GameName%\demoGH.cmd"
del /s /q /f "%gamesroot%\%GameName%\demoZY.cmd"
del /s /q /f "%gamesroot%\%GameName%\demoM.cmd"
del /s /q /f "%gamesroot%\%GameName%\filesize.vbs"
del /s /q /f "%gamesroot%\%GameName%\fix1.tmp"
del /s /q /f "%gamesroot%\%GameName%\fix2.tmp"
del /s /q /f "%gamesroot%\%GameName%\fix3.tmp"
del /s /q /f "%gamesroot%\%GameName%\gameInitializer.rgi"
del /s /q /f "%gamesroot%\%GameName%\gameInstall.rgi"
del /s /q /f "%gamesroot%\%GameName%\launch.ini"
del /s /q /f "%gamesroot%\%GameName%\RAunWrap.cmd"
del /s /q /f "%gamesroot%\%GameName%\rawk_licensekeys.reg"
del /s /q /f "%gamesroot%\%GameName%\rawk_prefs.reg"
del /s /q /f "%gamesroot%\%GameName%\rawk_reset.reg"
del /s /q /f "%gamesroot%\%GameName%\rgastub.bin"
del /s /q /f "%gamesroot%\%GameName%\rga_stub_bypass.reg"
del /s /q /f "%gamesroot%\%GameName%\rga_stub_remove.reg"
del /s /q /f "%gamesroot%\%GameName%\rgs_open_default.reg"

del /s /q /f "%gamesroot%\%GameName%\.ini"
del /s /q /f "%gamesroot%\%GameName%\ghdbtemp.cmd"
del /s /q /f "%gamesroot%\%GameName%\zydbtemp.cmd"

del /s /q /f "%gamesroot%\%GameName%\ghdb_core_installed_ver.cmd"
del /s /q /f "%gamesroot%\%GameName%\zydb_core_installed_ver.cmd"
del /s /q /f "%gamesroot%\%GameName%\ghdb_core_available_ver.cmd"
del /s /q /f "%gamesroot%\%GameName%\zydb_core_available_ver.cmd"
del /s /q /f "%gamesroot%\%GameName%\ghdb_core_running_ver.cmd"
del /s /q /f "%gamesroot%\%GameName%\zydb_core_running_ver.cmd"

del /s /q /f "%gamesroot%\%GameName%\core_rawk_cleanup_loader.cmd"
del /s /q /f "%gamesroot%\%GameName%\core_rawk_cleanup_root.cmd"

:end

if %testmode%==1 (
	echo [core_rawk_cleanup_loader : finished]
	pause>nul
)
