g_tableConfig = {}
DEFAULT_LOG_URL     = "http://logging.gamehouse.com/arcade/sites.html?"
DEFAULT_ITM_URL     = "http://switchboard.real.com/arcade/feeds.html?mode=payload&env=production&client=web&action=bundle_install&"
TRYMEDIA_LOG_URL    = "http://logging.gamehouse.com/arcade/sites.html?"
TRYMEDIA_ITM_URL    = "http://itm.trymedia.com/itm/installer/initializeGameInstall?"
ZYLOM_LOG_URL       = "http://logging.gamehouse.com/arcade/sites.html?"
ZYLOM_ITM_URL       = "http://itm.gamehouse.com/itm/installer/initializeGameInstall?"
DEFAULT_UPG_BASE    = "http://switchboard.real.com/arcade/feeds.html?mode=upg&env=production&client=web&action=bundle_install&"
DEFAULT_PLUGIN_BASE = "http://gamebundles.real.com/browserPlugin.packages?"
COOKIE_URL          = "http://gamebundles.real.com/installerPackages.packages"
V1_BASE_URL         = "http://switchboard.real.com/arcade/feeds.html?client=web&ractype=oldclient&action=download&gametype=download&dltype=bundle&"
g_tableConfig["realarcade.itmUrl"] = DEFAULT_ITM_URL
g_tableConfig["realarcade.logUrl"] = DEFAULT_LOG_URL
g_tableConfig["gamehouse.itmUrl"]  = DEFAULT_ITM_URL
g_tableConfig["gamehouse.logUrl"]  = DEFAULT_LOG_URL
g_tableConfig["tm.itmUrl"]         = TRYMEDIA_ITM_URL
g_tableConfig["tm.logUrl"]         = TRYMEDIA_LOG_URL
g_tableConfig["tm.simplefilename"] = 1
g_tableConfig["zylom.itmUrl"]         = ZYLOM_ITM_URL
g_tableConfig["zylom.logUrl"]         = ZYLOM_LOG_URL
g_tableConfig["zylom.simplefilename"] = 1
INSTALLER_VER = "2.6.0.451"
INSTALLER_LOCATION = "\\RealArcade\\Installer"
