/* Automatically generated include file (by parsebuild.pl)
   DO NOT EDIT THIS FILE.

   This file is property of Trymedia Systems, Inc.  
   (c) 2000 Trymedia Systems, Inc.

   It cannot be included in any project not belonging to 
   Trymedia Systems, Inc. */

var R_BUILD_MAJOR      = 2
var R_BUILD_MINOR      = 1
var R_BUILD_MAJORMINOR = 2.1
var R_BUILD_NUMBER     = 7
var R_BUILD_CHANGE     = "85861"
var R_BUILD_VERSION    = "Installer UI R2.1"
var R_BUILD_NAME       = "Installer UI"
var R_BUILD_BUILD      = "v2.1.7 [Installer UI R2.1]"
var R_BUILD_ALL        = "Installer UI v2.1.7 [Installer UI R2.1]"
var R_BUILD_HOST       = "vmbuild-x86-centos5-gcc.alc.gameco.biz"
var R_BUILD_USER       = ""
